# This is a basic workflow to help you get started with Actions
name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Build and Deploy
      uses: testthedocs/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BUILD_DIR: test/build/ # The folder, the action should deploy.
        BUILD_SCRIPT: npm install && npm build # The build script the action should run prior to deploying..


